import { Overview, Campaign, Setting, Market } from "./icons";
import { ISOTodate } from "../utils/date";

export const navLinkData = [
    {
        id: 1,
        title: "Overview",
        href: "/",
        icon: Overview,
    },
    {
        id: 2,
        title: "Campaign",
        href: "/campaigns",
        icon: Campaign,
    },
    {
        id: 3,
        title: "Market Intelligence",
        href: "/market",
        icon: Market,
    },
    {
        id: 4,
        title: "Account Settings",
        href: "/settings",
        icon: Setting,
    },
];

export const campaignsData = [
    {
        id: 667,
        campaignName: "obinna campaign",
        campaignDescription: "obinna campaign",
        startDate: ISOTodate("2008-12-09T22:29:52.767"),
        endDate: "2016-11-05T22:29:52.767",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 668,
        campaignName: "ACME Campaign",
        campaignDescription: "ACME Campaign",
        startDate: ISOTodate("2008-12-09T22:29:53.874"),
        endDate: "2016-11-05T22:29:53.875",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 669,
        campaignName: "ACME Campaign",
        campaignDescription: "ACME Campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.093"),
        endDate: "2016-11-05T22:29:54.093",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Active",
    },
    {
        id: 670,
        campaignName: "obinna campaign",
        campaignDescription: "obinna campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 671,
        campaignName: "MTN Campaign",
        campaignDescription: "MTN Campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Active",
    },
    {
        id: 672,
        campaignName: "obinna campaign",
        campaignDescription: "obinna campaign",
        startDate: ISOTodate("2024-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 673,
        campaignName: "MTN Campaign",
        campaignDescription: "MTN Campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Active",
    },
    {
        id: 674,
        campaignName: "obinna campaign",
        campaignDescription: "obinna campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 675,
        campaignName: "MTN Campaign",
        campaignDescription: "MTN Campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Active",
    },
    {
        id: 676,
        campaignName: "obinna campaign",
        campaignDescription: "obinna campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
    {
        id: 677,
        campaignName: "GLO Online Campaign",
        campaignDescription: "GLO Online Campaign",
        startDate: ISOTodate("2008-12-09T22:29:54.77"),
        endDate: "2016-11-05T22:29:54.77",
        digestCampaign: "No",
        linkedKeywords: ["obi", "nna"],
        dailyDigest: "daily",
        campaignStatus: "Inactive",
    },
];
